# Generated by Django 3.2.12 on 2022-03-01 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('title', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(blank=True, default=False)),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('cook_temp', models.IntegerField()),
                ('temp_system', models.CharField(max_length=255)),
                ('makes', models.IntegerField()),
                ('makes_descriptor', models.CharField(max_length=255)),
                ('personal_notes', models.TextField()),
                ('steps', models.JSONField(blank=True)),
                ('category', models.CharField(choices=[('Bre', 'Bre'), ('Lun', 'Lun'), ('Din', 'Din'), ('Des', 'Des')], default='Din', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
