# Generated by Django 3.2.12 on 2022-03-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220301_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
